[project]
description = "Method chaining for iterables and dictionaries in Python."
name = "pyochain"
readme = "README.md"
requires-python = ">=3.13"
version = "0.27.0"

dependencies = []

classifiers = ["License :: OSI Approved :: MIT License"]

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "maturin>=1.15.0",
    "pydoclint>=0.9.1",
    "pytest-benchmark>=5.2.3",
    "pytest-docflex",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "sdsort",
]
doc = ["mkdocstrings-python>=2.0.7", "zensical>=0.0.57"]
[tool.pydoclint]
arg-type-hints-in-docstring = true
arg-type-hints-in-signature = true
check-class-attributes = true
check-raises = true
check-return-types = true
check-yield = true
require-arg-section = true
require-inline-class-var-docs = true
require-return-section = true
require-return-section-when-returning-nothing = false
skip-checking-short-docstrings = true
style = "google"

[tool.uv.sources]
pytest-docflex = { git = "https://github.com/OutSquareCapital/pytest-docflex.git" }
sdsort = { git = "https://github.com/OutSquareCapital/sdsort.git", branch = "decorators-kind" }

[build-system]
build-backend = "maturin"
requires = ["maturin>=1.8,<2.0"]

[tool.maturin]
editable-profile = "dev"
manifest-path = "Cargo.toml"
module-name = "pyochain"
[tool.basedpyright]
reportExplicitAny = false
reportImportCycles = false
reportMissingSuperCall = false
typeCheckingMode = "all"
[tool.pytest.ini_options]
addopts = "--docflex --benchmark-skip"
testpaths = ["README.md", "docs", "pyochain", "tests"]
[tool.sdsort]
method-order = ["visibility", "behavior", "contract"]
"sort-by-name" = true
visibility-order = ["dunder", "protected", "private", "public"]
behavior-order = ["classmethod", "staticmethod", "property", "instancemethod"]
contract-order = ["abstractmethod", "abstract_override"]
