[project]
    description     = "Method chaining for iterables and dictionaries in Python."
    name            = "pyochain"
    readme          = "README.md"
    requires-python = ">=3.13"
    version         = "0.26.0"

    dependencies = []

    classifiers = ["License :: OSI Approved :: MIT License"]


[dependency-groups]
    dev = [
        "basedpyright>=1.39.9",
        "maturin>=1.14.1",
        "mkdocstrings-python>=2.0.5",
        "pydoclint>=0.9.1",
        "pytest-benchmark>=5.2.3",
        "pytest-cov>=7.0.0",
        "pytest-docflex",
        "pytest>=9.1.1",
        "rich>=15.0.0",
        "ruff>=0.16.1",
        "sdsort>=1.1.0",
        "toml>=0.10.2",
        "zensical>=0.0.53",
    ]
[tool.pydoclint]
    arg-type-hints-in-docstring                   = true
    arg-type-hints-in-signature                   = true
    check-class-attributes                        = true
    check-raises                                  = true
    check-return-types                            = true
    check-yield                                   = true
    require-arg-section                           = true
    require-return-section                        = true
    require-return-section-when-returning-nothing = false
    skip-checking-short-docstrings                = true
    style                                         = "google"

[tool.uv.sources]
    pytest-docflex = { git = "https://github.com/OutSquareCapital/pytest-docflex.git" }

[build-system]
    build-backend = "maturin"
    requires      = ["maturin>=1.8,<2.0"]

[tool.maturin]
    manifest-path = "rust/Cargo.toml"
    module-name   = "pyochain.rs"
    python-source = "src"
[tool.basedpyright]
    reportExplicitAny      = false # As a library we have no choice but to use `Any` in some places, so we disable this check.
    reportImportCycles     = false
    reportMissingSuperCall = false
    typeCheckingMode       = "all"
[tool.pytest.ini_options]
    addopts   = "--docflex --benchmark-skip"
    testpaths = ["README.md", "docs", "src/pyochain", "tests"]
