[lint]
    external = ["DOC"]
    ignore = [
        "unnecessary-call-around-sorted",                    # Can be a behavioral change who introduce subtle bugs
        "unnecessary-map",
        "missing-trailing-comma",
        "missing-trailing-comma",
        "missing-copyright-notice",
        "non-imperative-mood",
        "line-too-long",
        "line-contains-todo",
        "line-contains-hack",
        "import-outside-top-level",
        "too-many-public-methods",
        "magic-value-comparison",
        "docstring-in-stub",
        "assert",
        "suspicious-pickle-usage",                    # We don't care about cryptographic security
        "suspicious-eval-usage",                    # We don't care about eval
        "suspicious-non-cryptographic-random-usage",                    # We don't care about cryptographic security
        "suspicious-pickle-import",                    # We don't care about insecure modules
        "hardcoded-sql-expression",
        "private-member-access",
        "print",
        "runtime-cast-value",
        "missing-todo-author",
        "missing-todo-link",
        "relative-imports",
        "pytest-raises-too-broad", # We don't care about pytest raises too broad
        "subclass-builtin",        # We know what we do when subclassing builtins
    ]

    preview = true
    select  = ["ALL"]
[format]
    docstring-code-format = true
    preview               = true
    [lint.pydocstyle]
        convention = "google"
    [lint.per-file-ignores]
        "t.py" = ["missing-return-type-undocumented-public-function", "undocumented-public-module", "undocumented-public-class", "undocumented-public-method", "undocumented-public-function"]
        "tests/*" = [
            "D",       # We don't want to document tests
            "DOC",     # We don't want to document tests
            "docstring-missing-returns",
            "call-datetime-without-tzinfo",
            "boolean-type-hint-positional-argument",
            "unnecessary-dunder-call", # Dunders calls are more convenients in tests
        ]
