name: Quality Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  quality:
    name: Type checking, linting, and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --group dev

      - name: lint Rust files
        run: uv run cargo clippy --workspace

      - name: format Rust files
        run: cargo fmt --all -- --check

      - name: Lint Python files
        run: uv run ruff check .

      - name: Check Python formatting
        run: uv run ruff format --check --preview .

      - name: Check python ordering
        run: uv run sdsort . --stubs --check

      - name: Check stub docstrings
        run: |
          shopt -s globstar
          uv run pydoclint pyochain/**/*.pyi

      - name: Type-check Python package
        run: uv run basedpyright .

  compile:
    name: Compile on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    needs: quality
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Check compilation
        run: uv run --python ${{ matrix.python-version }} --group dev cargo check --workspace --all-targets
