name: Quality Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  quality:
    name: Quality - ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - rust-lint
          - rust-format
          - python-lint
          - python-format
          - python-order
          - stub-docstrings
          - python-types
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run quality check
        run: uv run cargo clippy --workspace
        if: matrix.check == 'rust-lint'

      - name: Run quality check
        run: cargo fmt --all -- --check
        if: matrix.check == 'rust-format'

      - name: Run quality check
        run: uv run ruff check .
        if: matrix.check == 'python-lint'

      - name: Run quality check
        run: uv run ruff format --check --preview .
        if: matrix.check == 'python-format'

      - name: Run quality check
        run: uv run sdsort . --stubs --check
        if: matrix.check == 'python-order'

      - name: Run quality check
        run: |
          shopt -s globstar
          uv run pydoclint pyochain/**/*.pyi
        if: matrix.check == 'stub-docstrings'

      - name: Run quality check
        run: uv run basedpyright .
        if: matrix.check == 'python-types'

  compile:
    name: Compile on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    needs: quality
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Check compilation
        run: uv run --python ${{ matrix.python-version }} --group dev cargo check --workspace --all-targets
